In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
import numpy 
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
print(np.__version__)

1.18.5


creating a numpy ndarrayobject

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[4,5,6]],[[6,7,8],[6,7,8,9,10]]])
print(arr)
print(type(arr))

[[list([1, 2, 3, 4, 5]) list([4, 5, 6])]
 [list([6, 7, 8]) list([6, 7, 8, 9, 10])]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a= np.array(456)
b= np.array([1,2,3,4,5,6,7])
c= np.array([[1,2,3,4,5,],[6,7,8,9,10]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
import numpy as np
a= np.array(456)
b= np.array([1,2,3,4,5,6,7])

In [ ]:
import numpy as np
b= np.array([1,2,3,4,5,6,7])
print(b[2]+b[4])

8


In [ ]:
import numpy as np
c= np.array([[1,2,3,4,5,],[6,7,8,9,10]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print('5th element on 2nd dim',c[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd dim 10


In [ ]:
import numpy as np
c= np.array([[[1,2,3,],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('Print the third element of second array of the first array: ', c[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
Print the third element of second array of the first array:  6


In [ ]:
import numpy as np
c= np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print(c)
print('last element from 2nd dimension:',c[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
last element from 2nd dimension: 10


In [ ]:
import numpy as np
c= np.array([1,2,3,4,5,6,7,8,9,10])
print(c[0:6])
print(c[1:6])
print(c[3:7])
print(c[1:5])
print(c[5:])
print(c[6:])


[1 2 3 4 5 6]
[2 3 4 5 6]
[4 5 6 7]
[2 3 4 5]
[ 6  7  8  9 10]
[ 7  8  9 10]


In [ ]:
import numpy as np
d= np.array([1,2,3,4,5,6,7,8,9,10,34,76,56,78,13])
print(d[-3:-1])
print(d[1:5:2])
print(d[2:5:3])
print(d[::5])

[56 78]
[2 4]
[3]
[ 1  6 34]


In [ ]:
import numpy as np
c= np.array([[1,2,3,4,5,6,7,8],[9,10,34,76,56,78,13,54]])
print(c[0:2,1:4])

[[ 2  3  4]
 [10 34 76]]


In [ ]:
import numpy as np
d= np.array([1,2,3,4,5,6,7,8,9,10,34,76,56,78,13])
print(d.dtype)

int64


In [ ]:
import numpy as np
d= np.array(['adi','harsh','gaurang','rohan','kaizar','yatin'])
print(d.dtype)


<U7


In [ ]:
import numpy as np
c= np.array([1,45,34,2,56,89,79,4,34,52,34])
newarry=c.astype(int)
print(newarry)
print(newarry.dtype)
print(c.dtype)

[ 1 45 34  2 56 89 79  4 34 52 34]
int64
int64
